### ISSUE TITLE
App didn't work..........

### ISSUE THREAD

**Issue by udithaPS** [ShinobiControls/grids-weather-app#4]
I used latest shinobigrid trail version.. After entering license keys for both places it gives error...

2014-12-22 14:17:02.399 GridsWeatherDemo[5902:60b] No ShinobiControls license key given - please set the license key. e.g. in AppDelegate.m #import <ShinobiEssentials/ShinobiEssentials.h> and add the following code [ShinobiEssentials setLicenseKey:@"<your trial license key>"];

if i do as error says it gives same error...
can anyone tell me how to fix this one.....

**Comment by alisonrclarke** [comment]
This project was a bit out-of-date. I've just updated it to work with the latest versions of iOS, Xcode and ShinobiGrids. The way to set the license key has also changed in recent versions of ShinobiGrids, so try checking out the latest version of the code, then open up ViewController.m and edit the following line in `viewDidLoad:` to add your trial license key:

    [ShinobiDataGrids setLicenseKey:@""]; // TODO: add your trial license key here!

**Comment by samelkh** [comment]
Hi Alison, I am having the same issue. I just downloaded the GridGallery and followed your instructions, but I am  getting the sam error. 2015-09-12 21:12:07.296 GridsGallery[32032:19899243] No ShinobiControls license key given - please set the license key. e.g. in AppDelegate.m #import <ShinobiEssentials/ShinobiEssentials.h> and add the following code [ShinobiEssentials setLicenseKey:@"<your trial license key>"];

Added the license key in GridsGalleryCommonViewController.m I believe that is the place. Can you help out? Thanks
